export const categories: string[] = ['Restaurants','Hotels','Hospitals','Schools','Shopping','Automotive','Beauty','Spa',
    'Fitness','Dentists','Lawyers','Real Estate','Banks','Bus Stand','Pharmacies','Petrol Pumps','Pet Services','Home Services',
    'Coaching Centres','Tuition Classes','Colleges','Universities','Government Offices','Travel Agencies',
    'Tour Operators','Courier Services','Logistics Services','Event Management','Party Services','Wedding Services',
    'Banquet Halls','Caterers','Photographers','Doctors','Clinics','Diagnostic Centres','Labs','Repair Services',
    'Maintenance Services','Grocery Stores','Supermarket','Sweet Shops','Bakeries','Clothing Stores',
    'Apparel Stores','Mobile Stores','Electronics Stores','Cyber Cafes','Printing Services','Temples','Gurudwaras',
    'Churches','Mosques','NGOs','Charitable Organizations','Public Transport Services','Bus Services','Taxi Services',
    'Auto Services','Metro Services','Driving Schools','Car Rentals','Bike Rentals','Agricultural Services',
    'Equipment Dealers','Hardware Stores','Building Material Suppliers','Cement Dealers','AC Dealers',
    'AC Repair Services','AC Installation Services','General Physician','Pediatrician','Cardiologist',
    'Dermatologist','Gynecologist Obstetrician','Orthopedic Doctor','ENT Specialist Ear Nose Throat',
    'Ophthalmologist Eye Specialist','Dentist','Neurologist','Psychiatrist','Urologist','Nephrologist',
    'Gastroenterologist','Pulmonologist Chest Specialist','Oncologist Cancer Specialist','Endocrinologist',
    'Rheumatologist','Surgeon General','Plastic Surgeon','Physiotherapist','Homeopathy Doctor','Ayurvedic Doctor',
    'Unani Doctor','Sexologist','Immunologist','Geriatric Specialist Elderly Care','Occupational Therapist',
    'Speech Therapist','Dietitian Nutritionist','ATM','IT Company','Institute','Assistent',
    'Fine Dining Restaurants', 'Cafes', 'Fast Food Outlets', 'Food Courts', 'Bakeries & Confectioneries',
    'Sweet Shops', 'Buffet Restaurants', 'Multi Cuisine Restaurants', 'North Indian Restaurants',
    'South Indian Restaurants','Chinese Restaurants','Punjabi Dhabas','Seafood Restaurants',
    'Barbeque & Grill Restaurants','Biryani Outlets','Pizza Outlets','Burger Joints',
    'Sandwich & Snacks Corners','Juice Bars & Shakes Parlours','Ice Cream Parlours','Pubs & Bars','Resort',
    'Motel', 'Hostel', 'Luxury Hotel', 'Boutique Hotel', 'Guest House', 'Bed & Breakfast', 'Lodge', 
    'Capsule Hotel','Multi Speciality Hospitals', 'Children’s Hospital', 'Super Speciality Hospitals',
    'Private Hospital','Government Hospitals','Maternity Hospitals','Women’s Hospitals','Eye Hospitals',
    'ENT Hospitals','Orthopedic Hospitals','Cancer Hospitals','Heart Cardiac Hospitals','Neurology Hospitals',
    'Kidney Urology Hospitals','Gastroenterology Hospitals','Pulmonology Chest Hospitals','Skin & Cosmetic Hospitals',
    'Psychiatric Hospitals','Rehabilitation & Physiotherapy Centers','Ayurveda Hospitals','Homeopathy Hospitals',
    'Veterinary Hospitals','Emergency & Trauma Care Hospitals','Day Care Hospitals','Nursing Homes',
    'Charitable Trust Hospitals','Play Schools','Pre Primary Schools','Primary School','Middle Schools',
    'High School','Senior Secondary Schools','Government Schools','Private Schools', 'International School',
    'CBSE Schools','ICSE Schools','IB International Baccalaureate Schools','IGCSE Cambridge Schools',
    'Residential Boarding Schools','Montessori','Special Needs School','Malls & Shopping Complexes',
    'Grocery Stores', 'Kirana Shops', 'Clothing Stores', 'Apparel Boutiques','Footwear Stores','Jewellery Shops',
    'Watch Showrooms','Eyewear & Optical Stores','Electronics Stores','Mobile Phone Stores','Home Appliance Stores',
    'Furniture Stores','Home Décor & Furnishing Shops','Kitchenware Stores','Toy Stores','Bookstores & Stationery Shops',
    'Gift Shops','Handicrafts & Souvenir Shops','Sports Goods Stores','Cosmetic & Beauty Stores','Perfume Shops',
    'Pet Shops','Baby Product Stores','Car Dealers', 'Bike Dealers', 'Used Car Dealers', 'Used Bike Dealers',
    'Car Repair & Service Centres', 'Bike Repair & Service Centres', 'Car Wash & Detailing','Car Accessories Shops',
    'Bike Accessories Shops','Car Spare Parts Dealers','Bike Spare Parts Dealers','Tyre Shops','Battery Dealers',
    'Car Insurance Providers','Bike Insurance Providers','Car Finance & Loan Providers','Bike Finance & Loan Providers',
    'Car Rentals','Bike Rentals','Driving Schools','Vehicle Pollution Check Centres','Truck Dealers','Bus Dealers',
    'Commercial Vehicle Service Centres','Auto Rickshaw Dealers & Services','Salons', 'Beauty Parlours',
    'Unisex Salons', 'Ladies Beauty Parlours', 'Men’s Grooming Centres', 'Makeup Studios', 'Bridal Makeup Services', 
    'Hair Styling & Cutting', 'Hair Colouring Services','Nail Art & Nail Extensions','Skin Care Clinics',
    'Facial & Cleanup Services','Waxing & Threading Services','Mehndi Artists','Tattoo Studios','Cosmetic Clinics Botox Fillers etc',
    'Ayurvedic Beauty Centres','Herbal Beauty Clinics','Spa & Wellness Centres','Beauty Academies Training Institutes',
    'Day Spa', 'Medical Spa', 'Luxury Spa', 'Ayurvedic Spa', 'Thermal Spa','Gyms', 'Unisex Gyms', 'Women’s Fitness Centres', 
    'Personal Training Studios', 'Yoga Centres', 'Pilates Studios', 'Zumba Classes', 'Aerobics Centres', 'CrossFit Training Centres', 
    'Martial Arts Training Karate Taekwondo Judo','Boxing Training Centres','Mixed Martial Arts Training',
    'Dance Fitness Studios','Weight Loss Centres','Bodybuilding Gyms','Meditation & Wellness Centres','Online Fitness Classes',
    'Fitness Equipment Stores','Sports & Athletic Training Centres','Orthodontist', 'Pediatric Dentist',
    'Cosmetic Dentist', 'Oral Surgeon', 'Endodontist', 'Periodontist','Criminal Lawyer', 'Corporate Lawyer',
    'Family Lawyer', 'Immigration Lawyer', 'Tax Lawyer', 'Intellectual Property Lawyer','Residential Sales',
    'Commercial Sales', 'Property Management', 'Real Estate Investment', 'Rental Agency','Commercial Bank',
    'Investment Bank', 'Cooperative Bank', 'Credit Union', 'Online Bank','Retail Pharmacy',
    'Hospital Pharmacy', 'Compounding Pharmacy', 'Online Pharmacy','Petrol Station', 'Diesel Station',
    'CNG fillig station', 'EV Charging Station','Pet Grooming', 'Pet Boarding', 'Pet Training', 'Pet Sitting',
    'Veterinary Clinic','Plumbing', 'Electrical', 'Cleaning', 'Painting', 'Pest Control', 'Home Renovation',
    'Landscaping','CCTV Installation','Exam Coaching', 'Language Coaching', 'Skill Development', 'Career Counseling',
    'Computer training institutes','Math Tuition', 'Science Tuition', 'Language Tuition', 'Test Preparation','Institute',
    'Computer training institute','Ielts institute','Animation institute','Engineering College', 'Medical College', 
    'Arts College', 'Commerce College', 'Community College','Public University', 'Private University', 
    'Technical University', 'Open University','Municipal Office', 'Tax Office', 'Passport Office', 'Labor Office', 
    'Transport Office','Domestic Travel','International Travel','Cruise Booking','Adventure Travel','Honeymoon Packages',
    'Guided Tours','Adventure Tours','Cultural Tours','Wildlife Tours','Pilgrimage Tours','Domestic Courier',
    'International Courier', 'Same Day Delivery','Freight Forwarding', 'Warehousing', 'Transportation', 
    'Customs Clearance', 'Supply Chain Management','Corporate Events', 'Weddings', 'Concerts', 'Festivals',
    'Private Parties','Party Planning', 'Event Decor', 'Catering', 'Entertainment', 'Photography',
    'Wedding Planning', 'Bridal Makeup', 'Photography', 'Venue Booking', 'Catering','Wedding Halls', 
    'Conference Halls', 'Party Halls', 'Banquet Facilities','Wedding Catering', 'Corporate Catering', 
    'Buffet Catering', 'Specialty Cuisine Catering','Wedding Photographer', 'Event Photographer', 
    'Portrait Photographer', 'Product Photographer','Pediatrician', 'Cardiologist', 'Dermatologist',
    'Gynecologist Obstetrician', 'Orthopedic Doctor','Dentist','Neurologist','Psychiatrist',
    'ENT Specialist Ear Nose Throat','Ophthalmologist Eye Specialist','Neurologist','Psychiatrist',
    'Urologist','Nephrologist','Gastroenterologist','Endocrinologist','Rheumatologist','Surgeon',
    'Plastic Surgeon','Physiotherapist','Homeopathy Doctor','Ayurvedic Doctor','Unani Doctor','Sexologist',
    'Immunologist','Occupational Therapist','Speech Therapist','Medical Clinic', 'Dental Clinic', 'Wellness Clinic', 
    'Physiotherapy Clinic', 'Skin care clinic','Pathology Lab', 'Radiology Centre', 'Blood Test Centre', 
    'Health Checkup Centre','Medical Lab', 'Research Lab', 'Railway Station', 'Industrial Lab', 'Testing Lab','Appliance Repair', 
    'Electronics Repair', 'Furniture Repair', 'Watch Repair','Computer Laptop Repair','Building Maintenance', 
    'Garden Maintenance', 'Equipment Maintenance','Mini Mart','Organic Store','Discount Store','Traditional Sweets', 
    'Chocolate Shops', 'Bakery Sweets', 'Ice Cream Parlors','Cake Shop', 'Pastry Shop', 'Bread Shop', 'Artisan Bakery',
    'Men’s Wear', 'Women’s Wear', 'Children’s Wear', 'Ethnic Wear', 'Sportswear','Casual Wear', 'Formal Wear', 
    'Outdoor Wear', 'Undergarments','Smartphones', 'Feature Phones', 'Mobile Accessories', 'Repairs',
    'TV & Home Appliances', 'Computers', 'Gaming Consoles', 'Audio Equipment','Gaming Cafe', 'Internet Access',
    'Printing', 'Scanning','Digital Printing', 'Offset Printing', 'Screen Printing', '3D Printing','Hindu Temple', 
    'Jain Temple', 'Buddhist Temple','Main Gurudwara','Community Gurudwara','Catholic Church', 'Protestant Church', 'Orthodox Church',
    'Sunni Mosque', 'Shia Mosque', 'Community Mosque','Educational NGO', 'Healthcare NGO', 'Environmental NGO', 'Animal Welfare NGO',
    'Orphanages', 'Food Banks', 'Shelters','Bus Service', 'Metro Service', 'Taxi Service', 'Ride Sharing',
    'Local Bus', 'Intercity Bus', 'Tourist Bus','City Taxi', 'Outstation Taxi', 'Airport Taxi','Auto Rickshaw',
    'E-Rickshaw', 'Shared Auto','City Metro', 'Suburban Metro','Car Driving', 'Bike Driving', 'Commercial Vehicle Training', 
    'Self Drive Cars', 'Chauffeur Cars', 'Luxury Car Rentals','Scooter Rentals', 'Motorbike Rentals', 
    'Electric Bike Rentals','Farming Equipment', 'Crop Consultancy', 'Seed Supply','Construction Equipment', 
    'Agricultural Equipment', 'Industrial Equipment','Construction Hardware', 'Tools', 'Plumbing Supplies', 
    'Electrical Supplies','Cement', 'Steel', 'Bricks', 'Wood','Portland Cement', 'White Cement', 'Ready Mix Cement',
    'AC Gas Filling', 'AC Maintenance', 'AC Part Replacement', 'Window AC Installation', 'Split AC Installation', 'Central AC Setup',
    'Family Doctor', 'Internal Medicine', 'Preventive Care','Immigration consultants','Visa assistance',
    'Newborn Care', 'Child Vaccination', 'Child Nutrition','Heart Surgery', 'Heart Checkup','IT Company',
    'Digital Marketing Company','Web Design Development Company','Skin Care', 'Cosmetic Dermatology',
    'Laser Treatment','Pregnancy Care', 'Infertility Treatment', 'Gynecological Surgery','Joint Replacement', 
    'Fracture Treatment', 'Sports Injury','Hearing Care', 'Sinus Treatment', 'Throat Surgery','Cataract Surgery', 
    'Lasik', 'Glaucoma Treatment','General Dentistry', 'Orthodontics', 'Cosmetic Dentistry','Brain Surgery', 
    'Stroke Care', 'Epilepsy Treatment','Therapy', 'Medication Management', 'Addiction Treatment','Kidney Stone Treatment',
    'Urinary Tract Care','Dialysis', 'Kidney Transplant','Endoscopy', 'Liver Care', 'Digestive Disorder Treatment',
    'Asthma Care', 'COPD Treatment','Chemotherapy', 'Radiation Therapy', 'Cancer Surgery','Diabetes Care', 'Hormone Therapy',
    'Arthritis Treatment', 'Autoimmune Disease Care','Appendectomy', 'Hernia Repair','Cosmetic Surgery', 'Reconstructive Surgery',
    'Sports Injury Rehab', 'Post Surgery Rehab', 'Pain Management','Classical Homeopathy', 'Acute Illness Care',
    'Panchakarma', 'Herbal Medicine','Herbal Treatments', 'Massage Therapy','Male Sexual Health', 'Female Sexual Health',
    'Allergy Testing', 'Immune Disorder Care','Elderly Rehab', 'Chronic Illness Management','Workplace Injury Care', 
    'Hand Therapy','Speech Delay Therapy', 'Voice Therapy','Weight Loss Programs', 'Clinical Nutrition', 'Sports Nutrition', 
    'SBI Bank ATM', 'PNB Bank ATM', 'Indian Bank ATM', 'HDFC Bank ATM', 'ICIC Bank ATM', 'Axis Bank ATM', 
    'Punjab and Sind Bank ATM','Bank of Baroda ATM', 'Bank of India ATM', 'Union Bank of India ATM','Canara Bank ATM', 
    'Bank of Maharashtra ATM','Central Bank of India ATM','Indian Overseas Bank ATM', 'Indian Bank ATM','UCO Bank ATM'
  ];


export const subcategories = {
  'Restaurants': ['Fine Dining Restaurants', 'Cafes', 'Fast Food Outlets', 'Food Courts', 'Bakeries & Confectioneries', 'Sweet Shops', 'Buffet Restaurants', 'Multi-Cuisine Restaurants', 'North Indian Restaurants', 'South Indian Restaurants','Chinese Restaurants','Punjabi Dhabas','Seafood Restaurants','Barbeque & Grill Restaurants','Biryani Outlets','Pizza Outlets','Burger Joints','Sandwich & Snacks Corners','Juice Bars & Shakes Parlours','Ice Cream Parlours','Pubs & Bars'],
  'Hotels': ['Resort', 'Motel', 'Hostel', 'Luxury Hotel', 'Boutique Hotel', 'Guest House', 'Bed & Breakfast', 'Lodge', 'Capsule Hotel', 'Other'],
  'Hospitals': ['Multi-Speciality Hospitals', 'Children’s Hospital', 'Super-Speciality Hospitals', 'Private Hospital','Government Hospitals','Maternity Hospitals','Women’s Hospitals','Eye Hospitals','ENT Hospitals','Orthopedic Hospitals','Cancer Hospitals','Heart Cardiac Hospitals','Neurology Hospitals','Kidney Urology Hospitals','Gastroenterology Hospitals','Pulmonology Chest Hospitals','Skin & Cosmetic Hospitals','Psychiatric Hospitals','Rehabilitation & Physiotherapy Centers','Ayurveda Hospitals','Homeopathy Hospitals','Veterinary Hospitals','Emergency & Trauma Care Hospitals','Day Care Hospitals','Nursing Homes','Charitable Trust Hospitals'],
  'Schools': ['Play Schools','Pre-Primary Schools','Primary School','Middle Schools', 'High School','Senior Secondary Schools','Government Schools','Private Schools', 'International School','CBSE Schools','ICSE Schools','IB International Baccalaureate Schools','IGCSE Cambridge Schools','Residential Boarding Schools','Montessori', 'Special Needs School'],
  'Shopping': ['Malls & Shopping Complexes', 'Supermarkets', 'Grocery Stores', 'Kirana Shops', 'Clothing Stores', 'Apparel Boutiques','Footwear Stores','Jewellery Shops','Watch Showrooms','Eyewear & Optical Stores','Electronics Stores','Mobile Phone Stores','Home Appliance Stores','Furniture Stores','Home Décor & Furnishing Shops','Kitchenware Stores','Toy Stores','Bookstores & Stationery Shops','Gift Shops','Handicrafts & Souvenir Shops','Sports Goods Stores','Cosmetic & Beauty Stores','Perfume Shops','Pet Shops','Baby Product Stores'],
  'Automotive': ['Car Dealers', 'Bike Dealers', 'Used Car Dealers', 'Used Bike Dealers', 'Car Repair & Service Centres', 'Bike Repair & Service Centres', 'Car Wash & Detailing','Car Accessories Shops','Bike Accessories Shops','Car Spare Parts Dealers','Bike Spare Parts Dealers','Tyre Shops','Battery Dealers','Car Insurance Providers','Bike Insurance Providers','Car Finance & Loan Providers','Bike Finance & Loan Providers','Car Rentals','Bike Rentals','Driving Schools','Vehicle Pollution Check Centres','Truck Dealers','Bus Dealers','Commercial Vehicle Service Centres','Auto Rickshaw Dealers & Services'],
  'Beauty': ['Salons', 'Beauty Parlours', 'Unisex Salons', 'Ladies Beauty Parlours', 'Men’s Grooming Centres', 'Makeup Studios', 'Bridal Makeup Services', 'Hair Styling & Cutting', 'Hair Colouring Services','Nail Art & Nail Extensions','Skin Care Clinics','Facial & Cleanup Services','Waxing & Threading Services','Mehndi Artists','Tattoo Studios','Cosmetic Clinics Botox Fillers etc','Ayurvedic Beauty Centres','Herbal Beauty Clinics','Spa & Wellness Centres','Beauty Academies Training Institutes'],
  'Spa': ['Day Spa', 'Medical Spa', 'Luxury Spa', 'Ayurvedic Spa', 'Thermal Spa', 'Other'],
  'Fitness': ['Gyms', 'Unisex Gyms', 'Women’s Fitness Centres', 'Personal Training Studios', 'Yoga Centres', 'Pilates Studios', 'Zumba Classes', 'Aerobics Centres', 'CrossFit Training Centres', 'Martial Arts Training Karate Taekwondo Judo','Boxing Training Centres','Mixed Martial Arts Training','Dance Fitness Studios','Weight Loss Centres','Bodybuilding Gyms','Meditation & Wellness Centres','Online Fitness Classes','Fitness Equipment Stores','Sports & Athletic Training Centres'],
  'Dentists': ['Orthodontist', 'Pediatric Dentist', 'Cosmetic Dentist', 'Oral Surgeon', 'Endodontist', 'Periodontist', 'Other'],
  'Lawyers': ['Criminal Lawyer', 'Corporate Lawyer', 'Family Lawyer', 'Immigration Lawyer', 'Tax Lawyer', 'Intellectual Property Lawyer', 'Other'],
  'Real Estate': ['Residential Sales', 'Commercial Sales', 'Property Management', 'Real Estate Investment', 'Rental Agency', 'Other'],
  'Banks': ['Commercial Bank', 'Investment Bank', 'Cooperative Bank', 'Credit Union', 'Online Bank', 'Other'],
  'Pharmacies': ['Retail Pharmacy', 'Hospital Pharmacy', 'Compounding Pharmacy', 'Online Pharmacy', 'Other'],
  'Petrol Pumps': ['Petrol Station', 'Diesel Station', 'CNG fillig station', 'EV Charging Station', 'Other'],
  'Pet Services': ['Pet Grooming', 'Pet Boarding', 'Pet Training', 'Pet Sitting', 'Veterinary Clinic', 'Other'],
  'Home Services': ['Plumbing', 'Electrical', 'Cleaning', 'Painting', 'Pest Control', 'Home Renovation', 'Landscaping','CCTV Installation','Other'],
  'Coaching Centres': ['Exam Coaching', 'Language Coaching', 'Skill Development', 'Career Counseling','Computer training institutes', 'Other'],
  'Tuition Classes': ['Math Tuition', 'Science Tuition', 'Language Tuition', 'Test Preparation', 'Other'],
  'Institute': ['Computer training institute','Ielts institute','Animation institute'],
  'Colleges': ['Engineering College', 'Medical College', 'Arts College', 'Commerce College', 'Community College', 'Other'],
  'Universities': ['Public University', 'Private University', 'Technical University', 'Open University', 'Other'],
  'Government Offices': ['Municipal Office', 'Tax Office', 'Passport Office', 'Labor Office', 'Transport Office', 'Other'],
  'Travel Agencies': ['Domestic Travel', 'International Travel', 'Cruise Booking', 'Adventure Travel', 'Honeymoon Packages', 'Other'],
  'Tour Operators': ['Guided Tours', 'Adventure Tours', 'Cultural Tours', 'Wildlife Tours', 'Pilgrimage Tours', 'Other'],
  'Courier Services': ['Domestic Courier', 'International Courier', 'Same-Day Delivery', 'Logistics Services', 'Other'],
  'Logistics Services': ['Freight Forwarding', 'Warehousing', 'Transportation', 'Customs Clearance', 'Supply Chain Management', 'Other'],
  'Event Management': ['Corporate Events', 'Weddings', 'Concerts', 'Festivals', 'Private Parties', 'Other'],
  'Party Services': ['Party Planning', 'Event Decor', 'Catering', 'Entertainment', 'Photography', 'Other'],
  'Wedding Services': ['Wedding Planning', 'Bridal Makeup', 'Photography', 'Venue Booking', 'Catering', 'Other'],
  'Banquet Halls': ['Wedding Halls', 'Conference Halls', 'Party Halls', 'Banquet Facilities', 'Other'],
  'Caterers': ['Wedding Catering', 'Corporate Catering', 'Buffet Catering', 'Specialty Cuisine Catering', 'Other'],
  'Photographers': ['Wedding Photographer', 'Event Photographer', 'Portrait Photographer', 'Product Photographer', 'Other'],
  'Doctors': ['Pediatrician', 'Cardiologist', 'Dermatologist', 'Gynecologist Obstetrician', 'Orthopedic Doctor','Dentist','Neurologist','Psychiatrist','ENT Specialist Ear Nose Throat','Ophthalmologist Eye Specialist','Neurologist','Psychiatrist','Urologist','Nephrologist','Gastroenterologist','Endocrinologist','Rheumatologist','Surgeon','Plastic Surgeon','Physiotherapist','Homeopathy Doctor','Ayurvedic Doctor','Unani Doctor','Sexologist','Immunologist','Occupational Therapist','Speech Therapist'],
  'Clinics': ['Medical Clinic', 'Dental Clinic', 'Wellness Clinic', 'Physiotherapy Clinic', 'Skin care clinic', 'Other'],
  'Diagnostic Centres': ['Pathology Lab', 'Radiology Centre', 'Blood Test Centre', 'Health Check-up Centre', 'Other'],
  'Labs': ['Medical Lab', 'Research Lab', 'Industrial Lab', 'Testing Lab', 'Other'],
  'Repair Services': ['Appliance Repair', 'Electronics Repair', 'Furniture Repair', 'Watch Repair','Computer Laptop Repair', 'Other'],
  'Maintenance Services': ['Building Maintenance', 'Garden Maintenance', 'Equipment Maintenance', 'Other'],
  'Grocery Stores': ['Supermarket', 'Mini-Mart', 'Organic Store', 'Discount Store', 'Other'],
  'Supermarkets': ['Hypermarket', 'Neighborhood Store', 'Discount Supermarket', 'Other'],
  'Sweet Shops': ['Traditional Sweets', 'Chocolate Shops', 'Bakery Sweets', 'Ice Cream Parlors', 'Other'],
  'Bakeries': ['Cake Shop', 'Pastry Shop', 'Bread Shop', 'Artisan Bakery', 'Other'],
  'Clothing Stores': ['Men’s Wear', 'Women’s Wear', 'Children’s Wear', 'Ethnic Wear', 'Sportswear', 'Other'],
  'Apparel Stores': ['Casual Wear', 'Formal Wear', 'Outdoor Wear', 'Undergarments', 'Other'],
  'Mobile Stores': ['Smartphones', 'Feature Phones', 'Mobile Accessories', 'Repairs', 'Other'],
  'Electronics Stores': ['TV & Home Appliances', 'Computers', 'Gaming Consoles', 'Audio Equipment', 'Other'],
  'Cyber Cafes': ['Gaming Cafe', 'Internet Access', 'Printing', 'Scanning', 'Other'],
  'Printing Services': ['Digital Printing', 'Offset Printing', 'Screen Printing', '3D Printing', 'Other'],
  'Temples': ['Hindu Temple', 'Jain Temple', 'Buddhist Temple', 'Other'],
  'Gurudwaras': ['Main Gurudwara', 'Community Gurudwara', 'Other'],
  'Churches': ['Catholic Church', 'Protestant Church', 'Orthodox Church', 'Other'],
  'Mosques': ['Sunni Mosque', 'Shia Mosque', 'Community Mosque', 'Other'],
  'NGOs': ['Educational NGO', 'Healthcare NGO', 'Environmental NGO', 'Animal Welfare NGO', 'Other'],
  'Charitable Organizations': ['Orphanages', 'Food Banks', 'Shelters', 'Other'],
  'Public Transport Services': ['Bus Service', 'Metro Service', 'Taxi Service', 'Ride Sharing', 'Other'],
  'Bus Services': ['Local Bus', 'Intercity Bus', 'Tourist Bus', 'Other'],
  'Taxi Services': ['City Taxi', 'Outstation Taxi', 'Airport Taxi', 'Other'],
  'Auto Services': ['Auto Rickshaw', 'E-Rickshaw', 'Shared Auto', 'Other'],
  'Metro Services': ['City Metro', 'Suburban Metro', 'Other'],
  'Driving Schools': ['Car Driving', 'Bike Driving', 'Commercial Vehicle Training', 'Other'],
  'Car Rentals': ['Self-Drive Cars', 'Chauffeur Cars', 'Luxury Car Rentals', 'Other'],
  'Bike Rentals': ['Scooter Rentals', 'Motorbike Rentals', 'Electric Bike Rentals', 'Other'],
  'Agricultural Services': ['Farming Equipment', 'Crop Consultancy', 'Seed Supply', 'Other'],
  'Equipment Dealers': ['Construction Equipment', 'Agricultural Equipment', 'Industrial Equipment', 'Other'],
  'Hardware Stores': ['Construction Hardware', 'Tools', 'Plumbing Supplies', 'Electrical Supplies', 'Other'],
  'Building Material Suppliers': ['Cement', 'Steel', 'Bricks', 'Wood', 'Other'],
  'Cement Dealers': ['Portland Cement', 'White Cement', 'Ready Mix Cement', 'Other'],
  'AC Dealers': ['Window AC', 'Split AC', 'Portable AC', 'Central AC', 'Other'],
  'AC Repair Services': ['AC Gas Filling', 'AC Maintenance', 'AC Part Replacement', 'Other'],
  'AC Installation Services': ['Window AC Installation', 'Split AC Installation', 'Central AC Setup', 'Other'],
  'General Physician': ['Family Doctor', 'Internal Medicine', 'Preventive Care', 'Other'],
  'Assistent': ['Immigration consultants','Visa assistance'],
  'Pediatrician': ['Newborn Care', 'Child Vaccination', 'Child Nutrition', 'Other'],
  'Cardiologist': ['Heart Surgery', 'Heart Check-up', 'Other'],
  'IT Company': ['Digital Marketing Company','Web Design Development Company'],
  'Dermatologist': ['Skin Care', 'Cosmetic Dermatology', 'Laser Treatment', 'Other'],
  'Gynecologist Obstetrician': ['Pregnancy Care', 'Infertility Treatment', 'Gynecological Surgery', 'Other'],
  'Orthopedic Doctor': ['Joint Replacement', 'Fracture Treatment', 'Sports Injury', 'Other'],
  'ENT Specialist Ear Nose Throat': ['Hearing Care', 'Sinus Treatment', 'Throat Surgery', 'Other'],
  'Ophthalmologist Eye Specialist': ['Cataract Surgery', 'Lasik', 'Glaucoma Treatment', 'Other'],
  'Dentist': ['General Dentistry', 'Orthodontics', 'Cosmetic Dentistry', 'Other'],
  'Neurologist': ['Brain Surgery', 'Stroke Care', 'Epilepsy Treatment', 'Other'],
  'Psychiatrist': ['Therapy', 'Medication Management', 'Addiction Treatment', 'Other'],
  'Urologist': ['Kidney Stone Treatment', 'Urinary Tract Care', 'Other'],
  'Nephrologist': ['Dialysis', 'Kidney Transplant', 'Other'],
  'Gastroenterologist': ['Endoscopy', 'Liver Care', 'Digestive Disorder Treatment', 'Other'],
  'Pulmonologist Chest Specialist': ['Asthma Care', 'COPD Treatment', 'Other'],
  'Oncologist Cancer Specialist': ['Chemotherapy', 'Radiation Therapy', 'Cancer Surgery', 'Other'],
  'Endocrinologist': ['Diabetes Care', 'Hormone Therapy', 'Other'],
  'Rheumatologist': ['Arthritis Treatment', 'Autoimmune Disease Care', 'Other'],
  'Surgeon General': ['Appendectomy', 'Hernia Repair', 'Other'],
  'Plastic Surgeon': ['Cosmetic Surgery', 'Reconstructive Surgery', 'Other'],
  'Physiotherapist': ['Sports Injury Rehab', 'Post-Surgery Rehab', 'Pain Management', 'Other'],
  'Homeopathy Doctor': ['Classical Homeopathy', 'Acute Illness Care', 'Other'],
  'Ayurvedic Doctor': ['Panchakarma', 'Herbal Medicine', 'Other'],
  'Unani Doctor': ['Herbal Treatments', 'Massage Therapy', 'Other'],
  'Sexologist': ['Male Sexual Health', 'Female Sexual Health', 'Other'],
  'Immunologist': ['Allergy Testing', 'Immune Disorder Care', 'Other'],
  'Geriatric Specialist Elderly Care': ['Elderly Rehab', 'Chronic Illness Management', 'Other'],
  'Occupational Therapist': ['Workplace Injury Care', 'Hand Therapy', 'Other'],
  'Speech Therapist': ['Speech Delay Therapy', 'Voice Therapy', 'Other'],
  'Dietitian Nutritionist': ['Weight Loss Programs', 'Clinical Nutrition', 'Sports Nutrition', 'Other'],
  'ATM': ['SBI Bank ATM', 'PNB Bank ATM', 'Indian Bank ATM', 'HDFC Bank ATM', 'ICIC Bank ATM', 'Axis Bank ATM', 'Punjab and Sind Bank ATM','Bank of Baroda ATM', 'Bank of India ATM', 'Union Bank of India ATM','Canara Bank ATM', 'Bank of Maharashtra ATM','Central Bank of India ATM','Indian Overseas Bank ATM', 'Indian Bank ATM', 'UCO Bank ATM', 'Other'],
};